version: "3.8"

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neodo-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_HOSTNAME}:${PORT_NUMBER}/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      FLASK_SERVER_URL: ${FLASK_SERVER_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
    restart: unless-stopped
