spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${PORT_NUMBER}/${DATABASE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create # ?? ddl-auto ?? ??? ?? ??
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}


aws:
  s3:
    bucket: neodo-backend
    access-key: ${ACCESS-KEY}
    secret-key: ${SECRET-KEY}
    region: ap-northeast-2

