spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/${DATABASE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
flask:
  server:
    url: ${FLASK_SERVER_URL}
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
aws:
  s3:
    bucket: neodo-backends3bucket
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
    region: ap-northeast-2