name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy Spring Boot to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 443
          script: |
            cd /home/ec2-user/neodo_backend
            git reset --hard
            git clean -fd
            git pull origin develop

            docker compose down
            docker compose build --no-cache
            docker compose up -d